# documentation: https://github.com/tomfran/typo/wiki/Features

baseURL = 'https://sagarsarkale.org/'
languageCode = 'en-us'
title = 'Sagar Sarkale'
theme = 'Typo'

[taxonomies]
tag = 'tags'

# Google analytics code
googleAnalytics = "G-J90LP2EWLN"

[params]
# Meta description
description = "Sagar's digital corner"
favicon = "favicon.ico"
ogImage = "favicon-32x32.png"

# Appearance settings
theme = 'light'

# Intro on main page, content is markdown
homeIntroTitle = 'Hi'
homeIntroContent = """This is a sneak peek into my learning journey!"""

# Collection to display on home
homeCollectionTitle = 'Blog'
homeCollection = 'blog'

# Lists parameters
paginationSize = 100
listSummaries = false
listDateFormat = '2 Jan 2006'

# Breadcrumbs
breadcrumbs = true
pluralizelisttitles = false

# Social icons
[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/sagar-sarkale/"

[[params.social]]
name = "twitter"
url = "https://x.com/sagarrgh"

[[params.social]]
name = "email"
url = "https://mail.google.com/mail/?view=cm&fs=1&to=sagar@smallstep.ai&su=Hi%20Sagar&body=Let%27s%20chat!"

# Main menu pages
[[params.menu]]
name = "home"
url = "/"

[[params.menu]]
name = "blog"
url = "/blog"

[[params.menu]]
name = "work"
url = "/work/work"

[[params.menu]]
name = "random"
url = "/random"

[[params.menu]]
name = "about"
url = "/about"

# Syntax highligth on code blocks
[markup]
[markup.highlight]
style = 'xcode'
lineNos = true

[markup.tableOfContents]
    startLevel = 1
    endLevel = 3
    ordered = true


# Giscus comments
[params.giscus]
enable = false
repo = "user/repo"
repoid = "repoId"
category = "General"
categoryid = "categoryId"
mapping = "pathname"
theme = "preferred_color_scheme"



