# documentation: https://github.com/tomfran/typo/wiki/Features

baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Sagar Sarkale'
theme = 'Typo'

[taxonomies]
tag = 'tags'

# Google analytics code
googleAnalytics = "G-xxxxxxxxx"

[params]
# Meta description
description = "A Tech Blog"

# Appearance settings
theme = 'auto'

# Intro on main page, content is markdown
homeIntroTitle = 'Hi, this is a sneak peek into my learning journey!'
homeIntroContent = """
I am me and you are you.
"""

# Collection to display on home
homeCollectionTitle = 'Posts'
homeCollection = 'posts'

# Lists parameters
paginationSize = 100
listSummaries = true
listDateFormat = '2 Jan 2006'

# Breadcrumbs
breadcrumbs = true

# Social icons
[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/user/"

# [[params.social]]
# name = "medium"
# url = "https://medium.com/@user"

[[params.social]]
name = "twitter"
url = "https://x.com/user"

# Main menu pages
[[params.menu]]
name = "home"
url = "/"

[[params.menu]]
name = "posts"
url = "/posts"

[[params.menu]]
name = "about"
url = "/about"

# Syntax highligth on code blocks
[markup]
[markup.highlight]
style = 'algol'

# Giscus comments
[params.giscus]
enable = false
repo = "user/repo"
repoid = "repoId"
category = "General"
categoryid = "categoryId"
mapping = "pathname"
theme = "preferred_color_scheme"


